import Banner from "../components/Banner";
import Header from "../components/Header";
import "../styles/globals.css";

export const metadata = {
  title: "Dr Studio - Drones",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-7xl">
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
